const router = require('express').Router()
const authMiddleware = require('../../middlewares/auth')
const auth = require('./auth')
const user = require('./user')
const state = require('./state')
const customer = require('./customer')
const hsn = require('./hsn')
const branch = require('./branch')
const goods = require('./goods')
const vendor = require('./vendor')
const client = require('./client')
const notification = require('./notification')
const dealer = require('./dealer')
const vedio = require('./vedio')
const faq = require('./faq')
const invoice = require('./invoice')
const privacy =require('./privacy')
const contact =require('./contact')
const internal =require('./internal')
router.use('/auth', auth)
//router.use('/state', authMiddleware)
router.use('/state', state)
//router.use('/invoice', authMiddleware)
router.use('/invoice', invoice)
//router.use('/user', authMiddleware)
router.use('/user', user)
router.use('/user', user)
router.use('/dealer', dealer)
router.use('/privacy',privacy)
router.use('/internal',internal)
router.use('/customer', customer)
//router.use('/hsn', authMiddleware)
router.use('/hsn', hsn)
//router.use('/branch', authMiddleware)
router.use('/branch', branch)
//router.use('/goods', authMiddleware)
router.use('/goods', goods)
router.use('/vendor', vendor)
//router.use('/client', authMiddleware)
router.use('/client', client)
//router.use('/notification', authMiddleware)
router.use('/notification', notification)
//router.use('/vedio', authMiddleware)
router.use('/vedio', vedio)
router.use('/faq', faq)
module.exports = router