const router = require('express').Router()
const authMiddleware = require('../../middlewares/auth')
const auth = require('./auth')
const user = require('./user')
const state = require('./state')
const customer = require('./customer')
const hsn = require('./hsn')
const branch = require('./branch')
const goods = require('./goods')
const vendor = require('./vendor')
const client = require('./client')
const notification = require('./notification')
const dealer = require('./dealer')
const vedio = require('./vedio')
const faq = require('./faq')
const invoice = require('./invoice')
const privacy =require('./privacy')
const contact =require('./contact')
const internal =require('./internal')
const about =require('./about')
const home =require('./home')
const goodsuser =require('./goodsuser')

//================ home page list API =============
router.use('/home', home)
//====================== End home page list API ================
router.use('/auth', auth)
// router.use('/about', authMiddleware)
  router.use('/about/update', authMiddleware)
    router.use('/about/create', authMiddleware)
router.use('/about', about)
router.use('/state/index', authMiddleware)
router.use('/state/create', authMiddleware)
router.use('/state/update', authMiddleware)
router.use('/state', state)
//router.use('/invoice', authMiddleware)
router.use('/invoice', invoice)
router.use('/contact/index', authMiddleware)
router.use('/contact', contact)
router.use('/user', user)
router.use('/dealer', authMiddleware)
router.use('/dealer', dealer)
 router.use('/privacy/create',authMiddleware)
router.use('/privacy/update',authMiddleware)
router.use('/privacy',privacy)
router.use('/internal',authMiddleware)
router.use('/internal',internal)
router.use('/customer', authMiddleware)
router.use('/customer', customer)
router.use('/hsn/create', authMiddleware)
router.use('/hsn/update', authMiddleware)

router.use('/hsn', hsn)
router.use('/branch', authMiddleware)
router.use('/branch', branch)
router.use('/goods', authMiddleware)
router.use('/goods', goods)
router.use('/goodsuser', authMiddleware)
router.use('/goodsuser', goodsuser)
router.use('/vendor', authMiddleware)
router.use('/vendor', vendor)
router.use('/client', authMiddleware)
router.use('/client', client)
router.use('/notification', authMiddleware)
router.use('/notification', notification)
router.use('/vedio', authMiddleware)
router.use('/vedio', vedio)
router.use('/faq/update', authMiddleware)
router.use('/faq/create', authMiddleware)
router.use('/faq', faq)
module.exports = router